### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito-text-js#21]
In general, the CSS code needs cleanup. Also, I'm not happy with some aspects of the design (typography and icons). If there's time, it would be great to improve this - or even have an altogether alternative theme (e.g. the classic: dark mode).

**Comment by Manan311** [comment]
Hello @rsimon 

I am not exactly sure what you mean by "CSS code needs cleanup" but I can add a dark mode if that is fine. To do this I will be using the darkmode.js library.

Before:
<img width="1276" alt="Screen Shot 2019-12-06 at 6 58 44 PM" src="https://user-images.githubusercontent.com/50086671/70364507-d6e9ef00-185a-11ea-802f-52ed6e71a466.png">

After:
<img width="1264" alt="Screen Shot 2019-12-06 at 6 58 53 PM" src="https://user-images.githubusercontent.com/50086671/70364483-c8033c80-185a-11ea-8044-3ed719bf3049.png">

Let me know what you think.

**Comment by rsimon** [comment]
Hi @Manan311,

thanks for this - I wasn't aware of darkmode.js. (But, of course, there's always a solution out there already ;-)

What I meant was a bit different though: it wasn't specifically about a dark mode. But about the potential to support different CSS themes for the annotation editor. I love the darkmode.js solution though. However I don't think it should be hard-wired into the core library.

Given that it could just as well sit outside of RecogitoJS, maybe it would be nicer to have an alternativ  `index.html` demo page, that shows how to use darkmode.js together with RecogitoJS.

I got some more comments on the [pull request](https://github.com/pelagios/recogito-text-js/pull/25) - will write them there.

**Comment by Manan311** [comment]
Okay so the temes relate to multiple css styles that support the annotations so like, one css could be light another could be dark another could be sky blue or something like that. And also the themes are for the annotations and not for the full page right?

**Comment by rsimon** [comment]
Yes, exactly. The "themes" would simply be alternative stylesheets that could be used and, as you say, are not for the page, but only for:

- the text annotation highlight spans
- the design of the editor popup

The current CSS styles, BTW, are located here:
https://github.com/pelagios/recogito-text-js/tree/master/recogito-annotation-editor/themes/default

**Comment by rsimon** [comment]
Won‘t be implemented for the time being.
