### ISSUE TITLE
Close on ESC key

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito-text-js#22]
Support closing of components with the ESC key. In particular, the editor as a whole, and the mini-dropdown in the comment section.

**Comment by MusaBajwa** [comment]
Hi there I would like to try to fix this.

**Comment by rsimon** [comment]
Hi @MusaBajwa,

great! In principle, this should mostly be a matter of attaching key handlers when the component mounts, and removing when it unmounts. (Ideally, it could be done with code snippet made re-useable as a React hook.) The main challenge, I think, will rather be to get everything up and running, and find your way around the codebase. 

As an initial pointer, the main editor popup component is here:
https://github.com/pelagios/recogito-text-js/blob/master/recogito-annotation-editor/src/editor/Editor.jsx

And the mini-dropdown menu is here:
https://github.com/pelagios/recogito-text-js/blob/master/recogito-annotation-editor/src/editor/widgets/comments/DropdownMenu.jsx

Does this look feasible to you? If you think you want to give it a try, fantastic! Don't hesitate to get in touch if you need help.

**Comment by MusaBajwa** [comment]
Thanks a lot for the help and guidance. I am going to give this a try and see what I can do.

**Comment by rsimon** [comment]
Great: another thing - I think you should be able to follow the example here...

https://github.com/pelagios/recogito-text-js/blob/master/recogito-annotation-editor/src/editor/useClickOutside.js

...which is being used here:

https://github.com/pelagios/recogito-text-js/blob/master/recogito-annotation-editor/src/editor/widgets/comments/DropdownMenu.jsx

Just that this code handles clicks outside a component, whereas for this issue it would need to listen for the Escape keypress.

**Comment by rsimon** [comment]
Implemented in the new repo.
