### ISSUE TITLE
Updating annotation causes leftover annotation SPAN

### ISSUE THREAD

**Issue by rsimon** [pelagios/recogito-text-js#29]
See notes here: https://github.com/pelagios/recogito-text-js/pull/18

**Comment by falafeljan** [comment]
@rsimon, did you fix this? i'm happy to have a look. to me it sounds as we have some kind of asynchronous rendering issue—maybe [`requestAnimationFrame`](https://developer.mozilla.org/en-US/docs/Web/API/window/requestAnimationFrame) could help to sequentialize calls?

**Comment by rsimon** [comment]
Hi @falafeljan,

the `element.normalize()` definitely seemed to do the trick. I'm assuming this forces the DOM to recompute in between, and properly carry out the two operations in sequence. `setTimeout` seems a bit risky to me. What would be a good wait time? (Although I guess a wait time of 1ms would make sure things happen later in the event loop?)

I also saw a reference to `requestAnimationFrame` somewhere when I googled for a solution, but didn't follow up. In short: if you find a solution that's more solid than my hack - that would be great. If not, I think the functionality is there now, so no big worries.

**Comment by falafeljan** [comment]
i've missed your commit! calling `setTimeout` with a timeout of 0 does something similar to `requestAnimationFrame` afaik. i'd generally suspect that `element.normalize()` does the trick here!

**Comment by rsimon** [comment]
BTW: I'm trying to organize the code a little better. Merge code into fewer projects, but split up those bits that I want to have available as separate modules for re-use elsewhere. I'm also hoping to get a shot at starting with RecogitoJS-like image annotation. Everything's going to move to a new Github org: https://github.com/recogito - but it will happen step by step, before I make a "formal move" from this repository.
